version: "3.8"

services:
    mariadb:
        image: mariadb:10.7
        restart: always
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: "yes"
            MARIADB_DATABASE: "${DATABASE_DB}"
            MARIADB_USER: "${DATABASE_USER}"
            MARIADB_PASSWORD_FILE: "${DATABASE_PASSWORD_FILE_CONTAINER}"
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - mariadb-data:/var/lib/mysql
            - ${DATABASE_PASSWORD_FILE_LOCAL}:${DATABASE_PASSWORD_FILE_CONTAINER}
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "5"

    adminer:
        image: adminer
        restart: always
        ports:
            - 127.0.0.1:8080:8080

volumes:
    mariadb-data:
